"""Blocks torsor writes into a prompt file, and the policy they carry.

The rules digest, the project primer and the model-routing policy are all the
same shape: render something the agent would otherwise spend tool calls
rediscovering, and merge it into an instructions file as a managed block that
can be refreshed without touching what the user wrote around it."""
from __future__ import annotations

import json
import re as _re
from pathlib import Path

from torsor_helper import guard
from torsor_helper.budget import truncate_to_tokens
from torsor_helper.config import TorsorConfig
from torsor_helper.operations._shared import _log_op
from torsor_helper.operations.commands import list_commands
from torsor_helper.store import Store


_RULES_START = "<!-- torsor:rules -->"

_RULES_END = "<!-- /torsor:rules -->"

def _charter_section(body: str, heading: str) -> str:
    """Lines under `## <heading>` up to the next H2 (empty string if absent)."""
    match = _re.search(rf"^##\s+{_re.escape(heading)}\s*$\n(.*?)(?=^##\s|\Z)", body, _re.MULTILINE | _re.DOTALL)
    return match.group(1).strip() if match else ""

def agent_rules(store: Store, config: TorsorConfig, *, max_tokens: int | None = None) -> str:
    """A compact, token-budgeted digest of the project's standing constraints —
    charter principles + machine-readable ADR rules — for agent prompt files
    (AGENTS.md / CLAUDE.md). Rules the agent sees at prompt time cost zero
    tool-call tokens per session, and the guard still enforces them in CI."""
    _log_op(store, "get_rules", "")
    sections: list[str] = []

    if store.paths.charter.exists():
        principles = _charter_section(store.read_note(store.paths.charter).body, "Non-negotiable principles")
        if principles:
            sections.append(f"### Non-negotiable principles\n{principles}")

    rules = guard.load_rules(store)
    if rules:
        lines = []
        for r in rules:
            scope = f" in `{r.scope}`" if r.scope and r.scope != "*.py" else ""
            message = f" — {r.message}" if r.message else ""
            lines.append(f"- {r.kind}: `{r.target}`{scope}{message} (per {r.source})")
        sections.append(
            "### Architecture rules (machine-enforced — `torsor guard` flags violations)\n" + "\n".join(lines)
        )

    if not sections:
        return ""
    digest = "## Project rules (torsor-helper)\n\n" + "\n\n".join(sections)
    budget = config.budgets.rules_tokens if max_tokens is None else max_tokens
    return truncate_to_tokens(digest, budget, config.budgets.chars_per_token)

def _write_managed_block(target, start: str, end: str, content: str) -> str:
    """Write/refresh a marker-delimited block in `target` (AGENTS.md,
    CLAUDE.md, …). Idempotent — re-running replaces the block, never duplicates."""
    block = f"{start}\n{content}\n{end}"
    target = Path(target)
    if target.exists():
        text = target.read_text(encoding="utf-8")
        if start in text and end in text:
            pre, rest = text.split(start, 1)
            post = rest.split(end, 1)[1]
            new = pre + block + post
        else:
            new = text.rstrip() + "\n\n" + block + "\n"
    else:
        new = block + "\n"
    target.write_text(new, encoding="utf-8")
    return str(target)

def write_rules_block(store: Store, config: TorsorConfig, target) -> str:
    return _write_managed_block(target, _RULES_START, _RULES_END, agent_rules(store, config))

def _rule_line(r) -> str:
    scope = f" in `{r.scope}`" if r.scope and r.scope != "*.py" else ""
    message = f" — {r.message}" if r.message else ""
    return f"- {r.kind}: `{r.target}`{scope}{message}"

def _scope_to_paths_glob(scope: str) -> str:
    """A guard rule's scope → a Claude Code `paths:` glob (matched relative to
    the project root).

    The two agree now: `*` stays inside a segment and `**` spans directories in
    both, so a scope naming a directory passes through unchanged. A bare `*.py`
    means "any .py, anywhere" in a scope, which spelled as a glob is `**/*.py`."""
    scope = scope or "*.py"
    return scope if "/" in scope else f"**/{scope}"

# HTML comments are stripped from a rule file before it enters context, so this
# provenance line costs zero tokens (Claude Code memory docs).
_SCOPED_PROVENANCE = "<!-- generated by `torsor rules --scoped` from {src}; edit the ADR, not this file -->"

def write_scoped_rules(store: Store, config: TorsorConfig) -> list:
    """Export the standing rules as *path-scoped* Claude Code rule files under
    .claude/rules/torsor/ — one per ADR, with `paths:` derived from each rule's
    guard scope — so an architecture rule enters context only when the agent
    touches a file it governs, instead of every session via a monolithic
    CLAUDE.md block. Charter principles have no scope and become an unscoped
    file (loaded every session, like CLAUDE.md). The directory is fully
    managed: a file torsor no longer produces is removed."""
    _log_op(store, "get_rules", "scoped")
    out_dir = store.paths.claude_rules_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    if store.paths.charter.exists():
        principles = _charter_section(store.read_note(store.paths.charter).body, "Non-negotiable principles")
        if principles:
            target = out_dir / "principles.md"
            target.write_text(
                f"# Non-negotiable principles (torsor)\n\n{principles.strip()}\n\n"
                + _SCOPED_PROVENANCE.format(src=".torsor/charter.md") + "\n",
                encoding="utf-8",
            )
            written.append(target)

    for note_path, title, rules in guard.load_rules_by_note(store):
        globs = sorted({_scope_to_paths_glob(r.scope) for r in rules})
        rel = note_path.relative_to(store.paths.root).as_posix()
        target = out_dir / note_path.name
        lines = ["---", "paths:", *(f"  - {json.dumps(g)}" for g in globs), "---", "", f"# {title}", ""]
        lines += [_rule_line(r) for r in rules]
        lines += ["", "Machine-enforced — `torsor guard` flags violations.", "",
                  _SCOPED_PROVENANCE.format(src=rel), ""]
        target.write_text("\n".join(lines), encoding="utf-8")
        written.append(target)

    keep = {p.name for p in written}
    for stale in out_dir.glob("*.md"):
        if stale.name not in keep:
            stale.unlink()
    return written

_PRIMER_START = "<!-- torsor:primer -->"

_PRIMER_END = "<!-- /torsor:primer -->"

_TOKEN_PLAYBOOK = """### Work token-efficiently
- Call `bootstrap_session()` ONCE at session start — never re-call it mid-session. (Skip it entirely when torsor's SessionStart hook already injected the digest.)
- Before reading files to "understand the project", try `recall(query)` / `get_intent(topic)` — prior decisions and the symbol map are already indexed.
- Use `impact(symbol)` instead of repo-wide grep to find callers.
- Don't re-derive what's in this primer; it is current as of the last `torsor primer --write`.
- `remember()` decisions and `handoff()` at session end so the next session skips rediscovery entirely."""

def project_primer(store: Store, config: TorsorConfig, *, max_tokens: int | None = None) -> str:
    """Token-saver: a budgeted, prompt-time project primer (what this is, how
    it's shaped, where things live, and token-efficient tool habits). Content
    an agent reads in the prompt file costs zero discovery tool-calls per
    session — the cheapest tokens are the ones never spent."""
    max_tokens = config.budgets.primer_tokens if max_tokens is None else max_tokens
    cpt = config.budgets.chars_per_token
    sections: list[str] = []

    for label, path, frac in [
        ("What this project is", store.paths.charter, 0.30),
        ("How it's architected", store.paths.system_patterns, 0.30),
        ("Repo map (key modules)", store.paths.map_overview, 0.20),
    ]:
        if path.exists():
            body = store.read_note(path).body.strip()
            text = truncate_to_tokens(body, int(max_tokens * frac), cpt)
            if text.strip():
                sections.append(f"### {label}\n{text}")

    cmds = list_commands(store)
    if cmds:
        lines = [f"- `{c['command']}`" + (f" — {c['note']}" if c["note"] else f" ({c['name']})") for c in cmds]
        sections.append("### Project commands (don't re-derive these)\n" + "\n".join(lines))

    sections.append(_TOKEN_PLAYBOOK)
    primer = "## Project primer (torsor-helper)\n\n" + "\n\n".join(sections)
    return truncate_to_tokens(primer, max_tokens, cpt)

def write_primer_block(store: Store, config: TorsorConfig, target, *, max_tokens: int | None = None) -> str:
    return _write_managed_block(
        target, _PRIMER_START, _PRIMER_END, project_primer(store, config, max_tokens=max_tokens)
    )

_MODELS_START = "<!-- torsor:models -->"

_MODELS_END = "<!-- /torsor:models -->"

# Default op -> tier policy. CHEAP = deterministic torsor lookups + mechanical
# maintenance that return exact answers (no reasoning). SMART = judgement/creation.
_CHEAP_OPS = [
    "recall", "get_intent", "find_files", "impact", "get_rules", "get_primer",
    "check_drift", "check_dependencies", "check_staleness", "verify", "map_repo",
    "consolidate", "list_commands", "recipes",
]

_SMART_WORK = [
    "designing architecture", "writing & refactoring code",
    "making decisions (record_decision)", "debugging novel failures",
]

def model_policy(store: Store, config: TorsorConfig) -> str:
    """A prompt-ready model-routing policy: which work runs on the cheap model vs
    the smart model. torsor declares it; the harness/agent routes by it."""
    cheap = config.models.cheap or "(unset — run: torsor models --cheap <model-id>)"
    smart = config.models.smart or "(unset — run: torsor models --smart <model-id>)"
    lines = [
        "## Model routing (torsor-helper — token thrift)",
        "",
        "Route each task to the cheapest model that can do it *correctly*:",
        "",
        f"- **Cheap model — `{cheap}`** for deterministic torsor lookups & mechanical work "
        f"that return EXACT answers (no reasoning needed): {' · '.join(_CHEAP_OPS)}, and replaying "
        f"recorded commands (`torsor commands --run`). These recur constantly — they don't need a frontier model.",
        f"- **Smart model — `{smart}`** for judgement & creation: {' · '.join(_SMART_WORK)}.",
    ]
    if config.models.fast:
        lines.append(f"- **Fast model — `{config.models.fast}`** for quick mid-tier turns when the cheap model is too weak but a frontier model is overkill.")
    lines += [
        "",
        "Run `torsor verify` (the deterministic guard+deps+staleness gate) on the "
        "cheap model as a loop / pre-commit completion check; route the *fix* after a "
        "failed verdict to the smart model.",
        "",
        "Rule of thumb: if torsor can answer it deterministically, use the cheap model; "
        "if it requires inventing something new, use the smart model.",
    ]
    return "\n".join(lines)

def model_policy_json(store: Store, config: TorsorConfig) -> dict:
    """Machine-readable model-routing policy for programmatic routers (any harness,
    not just prompt-reading agents). The Markdown form (`model_policy`) is for
    agents that read a rules file; this is for code that picks the model itself."""
    return {
        "cheap": config.models.cheap,
        "smart": config.models.smart,
        "fast": config.models.fast,
        "route": {"cheap": list(_CHEAP_OPS), "smart": list(_SMART_WORK)},
        "note": "Run the 'cheap' ops + command replays on the cheap model; reserve 'smart' "
                "for design/code/decisions. torsor declares the policy; the harness routes.",
    }

def write_model_policy(store: Store, config: TorsorConfig, target) -> str:
    return _write_managed_block(target, _MODELS_START, _MODELS_END, model_policy(store, config))
