from __future__ import annotations

from pathlib import Path

from torsor_helper.paths import TorsorPaths

CHARTER = """---
type: charter
status: active
tags: [charter]
---

# Project Charter

## What we are building
_Describe the product in 2-3 sentences._

## Why it exists
_The problem being solved and for whom._

## Non-negotiable principles
- _e.g. local-first; Markdown is the source of truth._
"""

SYSTEM_PATTERNS = """---
type: system-patterns
status: active
tags: [architecture]
---

# System Patterns

## Architecture overview
_Layers, modules, how they communicate._

## Conventions
_Naming, error handling, testing style._

## Patterns in use
- _e.g. thin MCP adapter over a tested operations layer._
"""

TECH_CONTEXT = """---
type: tech-context
status: active
tags: [architecture]
---

# Tech Context

## Stack & versions
_Languages, frameworks, runtime versions._

## Constraints
_Hard limits: deps, platforms, performance._
"""

FIRST_ADR = """---
type: decision
status: accepted
tags: [adr]
links: []
rules: []
---

# ADR 0001: Adopt torsor-helper

## Context
This project uses torsor-helper to persist architectural intent and memory.

## Decision
Markdown under `.torsor/` is the source of truth; the index is derived and disposable.

## Consequences
Memory is git-versioned and human-editable. Future ADRs may add machine-readable
`rules:` in frontmatter that the drift guard enforces (Phase 4).
"""

ACTIVE_CONTEXT = """---
type: active-context
status: active
tags: [active]
---

# Active Context

## Current focus
_What we are working on right now._

## Recent changes
_What just happened._

## Open questions
_Unresolved decisions._
"""

PROGRESS = """---
type: progress
status: active
tags: [active]
---

# Progress

## Done
## In progress
## Blocked
"""

MAP_OVERVIEW = """---
type: map
status: derived
tags: [map]
---

# Repository Map

_This file is regenerated by `torsor map` (Phase 3). Placeholder for now._
"""


def seed_files(paths: TorsorPaths) -> dict[Path, str]:
    """Return the mapping of file path -> seed content for `init` scaffolding."""
    return {
        paths.charter: CHARTER,
        paths.system_patterns: SYSTEM_PATTERNS,
        paths.tech_context: TECH_CONTEXT,
        paths.decisions_dir / "0001-adopt-torsor-helper.md": FIRST_ADR,
        paths.map_overview: MAP_OVERVIEW,
        paths.active_context: ACTIVE_CONTEXT,
        paths.progress: PROGRESS,
    }
